name: Deploy AWS Lambda Functions

on:
  release:
    types: [created]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
          
  update_verification_lambda:
    name: Update user verification lambda
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P verification-lambda
        
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ExviUserVerification
          zip_file: target/verification-lambda.jar
          
  update_sign_up_lambda:
    name: Update sign up lambda
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P sign-up-lambda
        
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ExviSignUp
          zip_file: target/sign-up-lambda.jar
          