name: Deploy to AWS Lambda

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  update_dependencies:
    name: deploy lambda dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 

      - name: Build dependencies only with Maven
        run: mvn -B package --file pom.xml -P fat-jar-no-lambdas
          
      - name: Set up output zip structure
        run: |
          mkdir java
          mkdir java/lib
          mv -f target/*.jar java/lib/
          
      - name: Zip output
        uses: vimtor/action-zip@v1
        with:
          files: java/
          dest: exvi-deps.zip
          
      - name: Publish zipped dependencies to AWS Lambda layer
        uses: taotao2345/aws-lambda-publishlayer@v1.0.0
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          layer_name: ExviServer
          zip_file: exvi-deps.zip
          
  update_verification_lambda:
    name: Update user verification lambda
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P verification-lambda
        
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ExviUserVerification
          source: target/*.jar
          runtime: java11
          
  update_sign_up_lambda:
    name: Update sign up lambda
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P sign-up-lambda
        
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ExviSignUp
          source: target/*.jar
          runtime: java11
          