name: Deploy to AWS Lambda

on:
  release:
    types: [ created ]
  push:
    branches:
      - kotlin
  workflow_dispatch:

jobs:

  update_aws_lambsa:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Maven Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build lambda
        run: mvn -B package --file pom.xml -P main-lambda
      - name: Deploy lambda
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ExviUserData
          zip_file: target/main-lambda.jar

      - name: Build dependencies only
        run: mvn -B package --file pom.xml -P fat-jar-no-lambdas

      - name: Set up output dependency zip structure
        run: |
          mkdir zip
          mkdir zip/java
          mkdir zip/java/lib
          mv -f target/*.jar zip/java/lib/

      - name: Zip dependency output
        uses: vimtor/action-zip@v1
        with:
          files: zip
          dest: exvi-deps.zip

      - name: Publish zipped dependencies to AWS Lambda layer
        uses: taotao2345/aws-lambda-publishlayer@v1.0.0
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          layer_name: ExviServer
          zip_file: exvi-deps.zip

      - name: Update lambda dependencies
        uses: callummackenzie/latest-lambda-layer-action@v0.11
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: ExviUserData

      - name: Trim lambda layers
        uses: callummackenzie/trim-lambda-layers-action@v0.2
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          layer_name: ExviServer
          version_keep_count: 4